### ISSUE TITLE
Suggested improvements to environment yaml and to include absolute path of "lib" folder in the python scripts

### ISSUE THREAD

**Issue by abolia** [WGLab/Phen2Gene#11]
Hi, 
I have been trying to work with Phen2Gene. It seems like a great tool. But I found some little issues, which I think would be great if resolved and can make it more user-friendly.
1) Issues with installation on Mac OSX: There are dependencies that are specific to Linux (like ld_impl_linux, libgcc-ng, libgfortran-ng and libstdcxx-ng). Also the tags for other dependencies are specific to Linux machines. For example: python=3.8.0=**h357f687_5**. "h357f687_5" is specific to Linux and I don't think that should not be included in the Yaml so as to make it compatible to Mac OSX as well. Just "python=3.8.0" should work fine for all machines.
This yaml file should work for all machines:
"
name: phen2gene
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py38_0
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - freetype=2.10.0  - icu=64.2
  - kiwisolver=1.1.0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libffi=3.2.1
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7
  - libpng=1.6.37
  - matplotlib-base=3.1.2
  - ncurses=6.1
  - networkx=2.4=py_0
  - numpy=1.17.3
  - openssl=1.1.1d
  - pandas=0.25.3
  - patsy=0.5.1=py_0
  - pip=19.3.1=py38_0
  - pyparsing=2.4.5=py_0
  - python=3.8.0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=8.0
  - scipy=1.3.2
  - seaborn=0.9.0=py_2
  - setuptools=42.0.2=py38_0
  - six=1.13.0=py38_0
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - tk=8.6.10
  - tornado=6.0.3
  - wheel=0.33.6=py38_0
  - xz=5.2.4
  - zlib=1.2.11
"
2) './lib' reference in several python scripts like: phen2gene.py, lib/weight_assignment.py, lib/calculation.py. If you are running phen2gene outside the folder, it would not throw any error just skip saying the HPO id is not a valid human phenotype rather than throwing an error on actual knowledgebase not found. It should be more explicit and user should be able to run phen2gene outside of the cloned repo. A nice thing would be to have setup.py that can install phen2gene and update path of knowledgebase etc based on where user wants to install it. 

Hope my suggestions are useful and I am excited to try phen2gene.
Thank you.

**Comment by jimhavrilla** [comment]
Hey, thanks for letting me know.  If you can assure that the YAML file
works with MacOS and Linux and wouldn't mind, could you perhaps fork the
repo and submit a Pull Request with the updated YAML file?

As for running it outside of the repo folder...the knowledgebase is quite
small, so this is not an issue we are particularly concerned about.  But
that is something we could make more flexible for sure.  Again, would
welcome a PR on this, but it is something I or Mengge could probably do
ourselves.

**Comment by abolia** [comment]
Yes, I have tried installing with the new yaml on both linux and Mac and it works fine. Infact I also compared the results for example/HPO_sample.txt and the results match 100% as well. I can submit a PR and you can test that it works on your system as well.
Thank you.

**Comment by jimhavrilla** [comment]
Fantastic!  Thanks a lot.  I'll look for it.

>

**Comment by abolia** [comment]
I opened the PR.

**Comment by jimhavrilla** [comment]
Thanks!  I am testing it out right now on Linux to make sure (unfortunately
I do not have access to macosx atm, but will take your word for it)

**Comment by jimhavrilla** [comment]
So part 1 of this issue is closed now, I will have to talk to @MenggeZhao about how to incorporate optional paths into his code so that `lib` can be moved elsewhere optionally.

**Comment by abolia** [comment]
> So part 1 of this issue is closed now, I will have to talk to @MenggeZhao about how to incorporate optional paths into his code so that `lib` can be moved elsewhere optionally.

Sounds good. Thanks for your help.

**Comment by jimhavrilla** [comment]
Thank _you_ for the PR.  Very helpful.  Hopefully sometime next week Mengge and I can tackle this a la `setuptools` or something like that.

**Comment by jimhavrilla** [comment]
closed by #16.
