### ISSUE TITLE
input file format 

### ISSUE THREAD

**Issue by luckysummer** [WGLab/Phen2Gene#20]
How can I use the input file with phenotype terms extracted manually to run the Phen2Gene process? if I use the EHR-phenotype to convert the term to HPO ID, which is different from the phenolyzer's input ?

**Comment by jimhavrilla** [comment]
Can you give me some more details?  Maybe some example files or code you tried to run?

**Comment by jimhavrilla** [comment]
Well, it has been some time with no response, so I will close this issue.  I will say the the [README](https://github.com/WGLab/Phen2Gene/README.md) shows the only necessary input to Phen2Gene is a file or string of HPO IDs.  I will re-open this issue if you are interested again in the future.
